### ISSUE TITLE
 chatgpt.initSession is not a function error

### ISSUE THREAD

**Issue by dudegladiator** [mtaupiq/wa-chatgpt#1]
during the time of installation
![Screenshot_20221219_043401](https://user-images.githubusercontent.com/66335106/208412108-2721cea3-8395-48a6-b602-655ba9d30ab0.png)
during the time of start
![Screenshot_20221219_043411](https://user-images.githubusercontent.com/66335106/208412128-ed4f7bbc-3425-4036-b31e-f19d41b04755.png)

**Comment by mtaupiq** [comment]
> during the time of installation ![Screenshot_20221219_043401](https://user-images.githubusercontent.com/66335106/208412108-2721cea3-8395-48a6-b602-655ba9d30ab0.png) during the time of start ![Screenshot_20221219_043411](https://user-images.githubusercontent.com/66335106/208412128-ed4f7bbc-3425-4036-b31e-f19d41b04755.png)

Error say net::ERR_CONNECTION_RESET, please check your connection again make sure you can open web.whatsapp.com,

**Comment by dudegladiator** [comment]
![image](https://user-images.githubusercontent.com/66335106/208435255-fc247b87-baa9-402d-ae53-a796252f4a51.png)
![image](https://user-images.githubusercontent.com/66335106/208435269-75a0e5b5-c0f1-4e61-a71b-582f6f0a226d.png)

why these a are coming

**Comment by mtaupiq** [comment]
> ![image](https://user-images.githubusercontent.com/66335106/208435255-fc247b87-baa9-402d-ae53-a796252f4a51.png) ![image](https://user-images.githubusercontent.com/66335106/208435269-75a0e5b5-c0f1-4e61-a71b-582f6f0a226d.png)
> 
> why these a are coming

QR Code for authenticated whatsapp, maybe your terminal didnot support, you can try another terminal

**Comment by dudegladiator** [comment]
![image](https://user-images.githubusercontent.com/66335106/208492011-38d31015-60ff-4ce2-97f6-cd4ceb1f022f.png)
This is error after qr code

**Comment by mtaupiq** [comment]
> ![image](https://user-images.githubusercontent.com/66335106/208492011-38d31015-60ff-4ce2-97f6-cd4ceb1f022f.png) This is error after qr code

Update chatgpt to latest version

**Comment by dudegladiator** [comment]
updated, same problem persist

**Comment by dudegladiator** [comment]
and what do you mean by update chatgpt
i have cloned again

**Comment by dudegladiator** [comment]
and where to save .env file 
i have saved in in wa-chatgpt folder where i am running terminal

**Comment by mtaupiq** [comment]
> and what do you mean by update chatgpt

This https://github.com/transitive-bullshit/chatgpt-api, make sure you are on latest version or you can try delete node_modules folder and run npm install

**Comment by dudegladiator** [comment]
![image](https://user-images.githubusercontent.com/66335106/208498599-7d6f7d14-6d81-4aed-859e-5efb586f268a.png)
my email is not invalid 

i have tried both way 
CHROME_PATH=C:\Program Files\BraveSoftware\Brave-Browser\Application/brave.exe
EMAIL=["example@gmail.com"]
PASSWORD=["password"]

and 

CHROME_PATH=C:\Program Files\BraveSoftware\Brave-Browser\Application/brave.exe
EMAIL=[example@gmail.com]
PASSWORD=[password]

in both of them same error
